/**
 * Faucet module constants.
 *
 * Mint + authority pubkeys are pinned to the localnet bootstrap fixtures
 * generated by `scripts/lib/bootstrap-init.ts`. The service refuses to
 * boot the keypair providers if `FAUCET_USDC_AUTHORITY_KEYPAIR_B64`
 * decodes to anything other than `EXPECTED_AUTHORITY` — an early-fail
 * guard against accidentally dispatching the localnet faucet against a
 * real mint on any cluster other than localnet.
 */

/** Localnet test-USDC mint pubkey. */
export const USDC_MINT_PUBKEY = 'F9NVj8dFsqxbCfytfmrEWDjdDhmpV1YrjRuxiusGr9Ys';

/** Expected mint authority pubkey — fail-fast assertion target. */
export const EXPECTED_AUTHORITY = 'VHixjUhygakXkJkpnMQDa2E71QhhSgF2Zz2rPdzaH9T';

/** USDC has 6 decimals. */
export const USDC_DECIMALS = 6;

/** Default faucet drip amount, expressed in whole USDC. */
export const DEFAULT_AMOUNT = 1000;

/** Hard ceiling on a single drip request, in whole USDC. */
export const MAX_AMOUNT = 10_000;

/** Minimum SOL airdrop (in lamports) when the recipient has a 0-balance wallet. */
export const MIN_FUNDING_LAMPORTS = 50_000_000; // 0.05 SOL

/** Per-wallet rate-limit window — one successful claim per 24h. */
export const RATE_LIMIT_TTL_SEC = 86_400;

/** Single-flight lock TTL, in seconds. */
export const LOCK_TTL_SEC = 30;
