import { RWT_MINTS, USDC_MINTS } from '@areal/sdk/network';

/**
 * Faucet module constants.
 *
 * The localnet test-USDC mint is sourced from `@areal/sdk` (`USDC_MINTS.localnet`)
 * — NOT a hardcoded literal. A test-validator reset rotates every on-chain
 * address; the SDK's localnet table is regenerated by
 * `scripts/sync-sdk-localnet-mints.sh` on each reset and shipped via an SDK
 * version bump, so the faucet auto-tracks the live mint instead of drifting.
 * (Pinning a literal here is exactly what caused the R20-era 500: the old
 * `F9NVj…` mint no longer existed after the 2026-05-18 reset and `mint_to`
 * failed.)
 *
 * The mint authority pubkey is an env-supplied boot-time safety pin
 * (`FAUCET_USDC_AUTHORITY`), resolved at module load — see
 * `resolveExpectedAuthority` below. The faucet module refuses to boot if the
 * `FAUCET_USDC_AUTHORITY_KEYPAIR_B64` keypair decodes to anything other than
 * that expected pubkey. This guards against accidentally dispatching the
 * localnet faucet against a real mint on any cluster other than localnet.
 */

/** Localnet test-USDC mint pubkey, sourced from the SDK (no drift on reset). */
export const USDC_MINT_PUBKEY = USDC_MINTS.localnet.toBase58();

/**
 * Default expected mint authority pubkey — the test-validator deployer.
 *
 * On localnet the faucet authority == the deployer keypair (the one that
 * created the test-USDC mint and holds its mint authority). The deployer
 * rotates on every test-validator reset, so this literal is only a FALLBACK:
 * the live value comes from the `FAUCET_USDC_AUTHORITY` env var (see
 * `resolveExpectedAuthority`). Keep the literal pointed at the current
 * deployer (`CRAKi…`, post 2026-05-18 reset) so a bare boot without the env
 * still pins to the right signer; on a reset, set `FAUCET_USDC_AUTHORITY`
 * to the new deployer pubkey rather than editing this file.
 */
export const DEFAULT_EXPECTED_AUTHORITY = 'CRAKiyq2eau8fiNxH2DMhTzry2Jn3kKmXnhZGnbdyFvp';

/**
 * Resolve the boot-time expected authority pubkey.
 *
 * Precedence: `FAUCET_USDC_AUTHORITY` env (the deployer pubkey supplied by the
 * deploy path) > `DEFAULT_EXPECTED_AUTHORITY` fallback. Sourcing from env means
 * a test-validator reset that rotates the deployer auto-propagates without a
 * code change — the same anti-drift property we get for the mint via the SDK.
 */
export function resolveExpectedAuthority(envValue?: string | null): string {
  const trimmed = envValue?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : DEFAULT_EXPECTED_AUTHORITY;
}

/** USDC has 6 decimals. */
export const USDC_DECIMALS = 6;

/** Default faucet drip amount, expressed in whole USDC. */
export const DEFAULT_AMOUNT = 1000;

/** Hard ceiling on a single drip request, in whole USDC. */
export const MAX_AMOUNT = 10_000;

/** Minimum SOL airdrop (in lamports) when the recipient has a 0-balance wallet. */
export const MIN_FUNDING_LAMPORTS = 50_000_000; // 0.05 SOL

/** Per-wallet rate-limit window — one successful claim per 24h. */
export const RATE_LIMIT_TTL_SEC = 86_400;

/** Single-flight lock TTL, in seconds. */
export const LOCK_TTL_SEC = 30;

// ---------------------------------------------------------------------------
// RWT faucet constants (devnet-gated SPL Transfer from treasury ATA).
//
// Distinct from the USDC faucet because:
//   - RWT mint authority lives on-chain in the RWT engine PDA (not deployer),
//     so the faucet CANNOT use MintTo. Instead it transfers from a pre-funded
//     treasury ATA owned by the deployer.
//   - The RWT faucet is enabled on devnet (the USDC one is localnet-only).
//   - Mint and treasury authority are sourced via the SDK / env, mirroring
//     the USDC anti-drift pattern.
// ---------------------------------------------------------------------------

/** Devnet RWT mint pubkey, sourced from the SDK. */
export const RWT_MINT_PUBKEY = RWT_MINTS.devnet.toBase58();

/** RWT has 6 decimals (matches the devnet on-chain mint). */
export const RWT_DECIMALS = 6;

/** Default RWT faucet drip amount, in whole RWT. */
export const DEFAULT_RWT_AMOUNT = 100;

/** Hard ceiling on a single RWT drip request, in whole RWT. */
export const MAX_RWT_AMOUNT = 1_000;

/**
 * Default expected RWT treasury authority pubkey — the devnet deployer that
 * holds the pre-funded RWT ATA at `78xAMq2cGKMumgDoAHiHJZxC3MD55Q1qEEiyQPvoLoMc`.
 *
 * Same fallback / env-override pattern as `DEFAULT_EXPECTED_AUTHORITY` — see
 * `resolveExpectedRwtTreasury`. On a deployer rotation, set
 * `FAUCET_RWT_TREASURY` in the env to the new pubkey rather than editing
 * this file.
 */
export const DEFAULT_EXPECTED_RWT_TREASURY = '8ddRxwGnC1MD5ZCf22eLAne77Rput8itQbTjMr93xYvq';

/**
 * Resolve the boot-time expected RWT treasury authority pubkey.
 *
 * Precedence: `FAUCET_RWT_TREASURY` env > `DEFAULT_EXPECTED_RWT_TREASURY`
 * fallback. Same anti-drift property as `resolveExpectedAuthority` — a
 * deployer rotation propagates via env without a code change.
 */
export function resolveExpectedRwtTreasury(envValue?: string | null): string {
  const trimmed = envValue?.trim();
  return trimmed && trimmed.length > 0 ? trimmed : DEFAULT_EXPECTED_RWT_TREASURY;
}
